import {
  IAutoViewCompilerMetadata,
  IAutoViewComponentProps,
} from "@autoview/interface";
import { ChatGptTypeChecker } from "@samchon/openapi";
import typia from "typia";

import { CodeGeneration, PlanGeneration } from "../passes";
import { IAutoViewVendor } from "../structures";

/**
 * Configuration of the {@link AutoViewAgent}.
 */
export interface IAutoViewConfig {
  /**
   * The vendor of the entire agent pipeline.
   */
  vendor: IAutoViewVendor;

  /**
   * The vendor of the code generation.
   *
   * If not provided, the same vendor as the `vendor` will be used.
   */
  codeVendor?: IAutoViewVendor;

  /**
   * The input schema to be transformed.
   */
  inputSchema: IAutoViewCompilerMetadata;

  /**
   * The name of the transform function generated by the agent.
   *
   * Give different names if you plan to generate multiple transform functions to prevent name conflicts.
   *
   * If not provided, the default name will be `transform`.
   *
   * @default "transform"
   */
  transformFunctionName?: string;
}

/**
 * Result of the {@link AutoViewAgent}.
 */
export interface IAutoViewResult {
  /**
   * (Intermediate reasoning) Initial analysis of the input schema.
   */
  initialAnalysis: string;

  /**
   * (Intermediate reasoning) Data exploration of the input schema.
   */
  dataExploration: string;

  /**
   * (Intermediate reasoning) Ideas of visualizations.
   */
  ideas: string;

  /**
   * (Intermediate reasoning) Reasoning of the visualization.
   */
  reasoning: string;

  /**
   * (Intermediate reasoning) Planning of the visualization.
   */
  planning: string;

  /**
   * (Intermediate reasoning) The analysis of the input schema and thinking process of the visualization planning.
   */
  analysis: string;

  /**
   * The TypeScript code of the transform function.
   *
   * This code includes several import statements, preventing it to include bunch of DTO interface declarations.
   */
  transformTsCode: string;
}

/**
 * The `AutoViewAgent`.
 *
 * This is the class that orchestrates the entire agent pipeline.
 */
export class AutoViewAgent {
  constructor(private config: IAutoViewConfig) {}

  /**
   * Execute the agent pipeline.
   *
   * It generates the TypeScript code of the transform function from the input schema into the AutoView component.
   *
   * @returns The result of the agent pipeline.
   */
  async generate(): Promise<IAutoViewResult> {
    const planGenerationAgent = new PlanGeneration.Agent();
    await planGenerationAgent.open();

    const codeGenerationAgent = new CodeGeneration.Agent();
    await codeGenerationAgent.open();

    const components = componentSchema();

    const plan = await planGenerationAgent.execute({
      vendor: this.config.vendor,
      inputSchema: this.config.inputSchema,
      componentSchema: components,
    });

    try {
      const { analysis, transformTsCode } = await codeGenerationAgent.execute({
        vendor: this.config.codeVendor ?? this.config.vendor,
        inputSchema: this.config.inputSchema,
        componentSchema: components,
        initialAnalysis: plan.initial_analysis,
        dataExploration: plan.data_exploration,
        ideas: plan.ideas,
        reasoning: plan.reasoning,
        planning: plan.planning,
        transformFunctionName: this.config.transformFunctionName ?? "transform",
      });

      return {
        initialAnalysis: plan.initial_analysis,
        dataExploration: plan.data_exploration,
        ideas: plan.ideas,
        reasoning: plan.reasoning,
        planning: plan.planning,
        analysis,
        transformTsCode,
      };
    } finally {
      try {
        await planGenerationAgent.close();
      } catch (error) {
        console.warn(`failed to close plan generation agent: ${error}`);
      }
      try {
        await codeGenerationAgent.close();
      } catch (error) {
        console.warn(`failed to close code generation agent: ${error}`);
      }
    }
  }
}

function componentSchema(): IAutoViewCompilerMetadata {
  if (!ChatGptTypeChecker.isObject(PARAMETERS)) {
    throw new Error("PARAMETERS is not an object.");
  }

  return {
    $defs: PARAMETERS.$defs,
    schema: PARAMETERS.properties["props"]!,
  };
}

const PARAMETERS = typia.llm.parameters<
  {
    props: IAutoViewComponentProps;
  },
  "chatgpt",
  {
    reference: true;
  }
>();
